# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
---
version: 2.1
description: |
  Create custom Twilio SMS notifications for CircleCI jobs

#reference https://www.twilio.com/docs/sms/send-messages#send-an-sms-with-twilios-api

commands:
  sendsms:
    description: Send SMS notifications using Twilio
    parameters:
      from:
        type: string
        default: ${TWILIO_FROM}
      to:
        type: string
        default: ${TWILIO_TO}
      body:
        description: The Body parameter includes the full text of the message you want to send, limited to 1600 characters.
        type: string
        default: "Notification from CircleCI. You have not yet customized your message."
      sid:
        type: string
        default: ${TWILIO_SID}
      authtoken:
        type: string
        default: ${TWILIO_TOKEN}
    steps:
      - run:
          name: Sending SMS
          command: |
              curl -X POST https://api.twilio.com/2010-04-01/Accounts/<< parameters.sid >>/Messages.json \
              --data-urlencode "From=<< parameters.from >>" \
              --data-urlencode "Body=<< parameters.body >>" \
              --data-urlencode "To=<< parameters.to >>" \
              -u << parameters.sid >>:<< parameters.authtoken >>
